session_name: telnet-client
suppress_history: false
windows:
  - window_name: Git
    panes:
      - lazygit

  - layout: even-horizontal
    panes:
      - shell_command: ${EDITOR} -S
        focus: true
      - yarn run dev
